#!/usr/bin/env bash
# build-universes.sh — Compile all 5 universe WASM crates and optimise them.
#
# Usage: ./build-universes.sh [--skip-opt]
#
# Outputs optimised .wasm files to yggdrasil-web/embedded/.
# Run this script before `cargo build` or `cargo test` to replace the stubs
# generated by yggdrasil-web/build.rs with real game WASMs.
#
# Requirements:
#   - Rust toolchain with wasm32-unknown-unknown target
#       rustup target add wasm32-unknown-unknown
#   - wasm-opt (from the binaryen package)
#       brew install binaryen  (macOS)
#       apt-get install binaryen  (Debian/Ubuntu)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UNIVERSES_DIR="$SCRIPT_DIR/universes"
EMBEDDED_DIR="$SCRIPT_DIR/yggdrasil-web/embedded"
SKIP_OPT="${1:-}"

echo "==> Building universe WASM crates (target: wasm32-unknown-unknown)"
cd "$UNIVERSES_DIR"
cargo build --release --target wasm32-unknown-unknown

WASM_DIR="$UNIVERSES_DIR/target/wasm32-unknown-unknown/release"
mkdir -p "$EMBEDDED_DIR"

echo "==> Copying and optimising WASMs → $EMBEDDED_DIR"
for game in snake tetris invaders pointset poker; do
    src="$WASM_DIR/universe_${game}.wasm"
    dst="$EMBEDDED_DIR/${game}.wasm"

    if [ "$SKIP_OPT" = "--skip-opt" ] || ! command -v wasm-opt &>/dev/null; then
        cp "$src" "$dst"
        size_kb=$(($(wc -c < "$src") / 1024))
        echo "  $game: ${size_kb}KB (unoptimised)"
    else
        wasm-opt -O3 --enable-mutable-globals "$src" -o "$dst"
        orig_kb=$(($(wc -c < "$src") / 1024))
        opt_kb=$(($(wc -c < "$dst") / 1024))
        echo "  $game: ${orig_kb}KB → ${opt_kb}KB"
    fi
done

echo ""
echo "==> Size budget check"
declare -A BUDGETS=([snake]=300 [tetris]=300 [invaders]=300 [pointset]=200 [poker]=600)
PASS=true
for game in snake tetris invaders pointset poker; do
    dst="$EMBEDDED_DIR/${game}.wasm"
    size_kb=$(($(wc -c < "$dst") / 1024))
    budget=${BUDGETS[$game]}
    if [ "$size_kb" -le "$budget" ]; then
        echo "  ✓ $game: ${size_kb}KB ≤ ${budget}KB"
    else
        echo "  ✗ $game: ${size_kb}KB > ${budget}KB EXCEEDS BUDGET"
        PASS=false
    fi
done

if [ "$PASS" = true ]; then
    echo ""
    echo "All universos compiled successfully. Run 'cargo test' to verify."
else
    echo ""
    echo "One or more universos exceed their size budget. Aborting." >&2
    exit 1
fi
